site_name: TDD with pytest
pages:
  - 'About': index.md
  - 'TDD Basics': tdd-basics.md
  - 'TDD Advanced': tdd-advanced.md
docs_dir: content
site_dir: build
theme: readthedocs
repo_url: https://github.com/vanzaj/tdd-pytest
extra_css: ['extra.css']
markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - toc:
      permalink: True
